CREATE TABLE "L_SUBSTANCE"
  (
    "PKIN" NUMBER NOT NULL ENABLE,
    "DSID" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    "MOLFILE" CLOB,
    "MD5_MOLFILE"        VARCHAR2(32 BYTE),
    "STANDARD_INCHI"     VARCHAR2(4000 BYTE),
    "STANDARD_INCHI_KEY" VARCHAR2(50 BYTE),
    "JOB_ID"             NUMBER,
    "SRC_ID"             NUMBER(*,0),
    CONSTRAINT "L_SUBSTANCE_PK" PRIMARY KEY ("PKIN") ENABLE
  );
COMMENT ON COLUMN "L_SUBSTANCE"."SRC_ID"
IS
  'The owner (ie: depositor) of this substance record. FK to C_SOURCE';
CREATE OR REPLACE TRIGGER "L_SUBSTANCE_ID_TRIG" BEFORE
  INSERT ON L_SUBSTANCE FOR EACH ROW WHEN (NEW.PKIN IS NULL) BEGIN
  SELECT L_SUBSTANCE_ID_SQ.NEXTVAL INTO :NEW.PKIN FROM DUAL;
END L_SUBSTANCE_ID_TRIG;
/
ALTER TRIGGER "L_SUBSTANCE_ID_TRIG" ENABLE;