CREATE TABLE "L_TARGET"
  (
    "PKIN"             NUMBER NOT NULL ENABLE,
    "DTID"             VARCHAR2(400 BYTE) NOT NULL ENABLE,
    "ORGANISM_SPECIES" VARCHAR2(200 BYTE),
    "ORGANISM_STRAIN"  VARCHAR2(200 BYTE),
    "ORGANISM_TAX_ID"  NUMBER,
    "NAME"             VARCHAR2(400 BYTE),
    "ACCESSION"        VARCHAR2(20 BYTE),
    "TYPE"             VARCHAR2(20 BYTE),
    "JOB_ID"           NUMBER(*,0),
    "SRC_ID"           NUMBER(*,0),
    CONSTRAINT "L_TARGET_PK" PRIMARY KEY ("PKIN") ENABLE
  );
COMMENT ON COLUMN "L_TARGET"."SRC_ID"
IS
  'The owner (ie: depositor) of this target record. FK to C_SOURCE';
CREATE OR REPLACE TRIGGER "L_TARGET_ID_TRIG" BEFORE
  INSERT ON L_TARGET FOR EACH ROW WHEN (NEW.PKIN IS NULL) BEGIN
  SELECT L_TARGET_ID_SQ.NEXTVAL INTO :NEW.PKIN FROM DUAL;
END L_TARGET_ID_TRIG;
/
ALTER TRIGGER "L_TARGET_ID_TRIG" ENABLE;